[package]
name = "onchg"
version = "0.1.0"
edition = "2021"

[features]
default = []
git = ["git2"]

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.4", features = ["derive"] }
# We only need local Git repo support. Default features enable remote clone & fetch.
git2 = { version = "0.18", optional = true, default-features = false }
ignore = "0.4.20"
patch = "0.7.0"
regex = "1.9.5"

[dev-dependencies]
indoc = "2.0.4"
tempfile = "3.8.0"
