name: test

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**/*.md'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  linux-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install libgit2
        run:  sudo apt-get install -y libgit2-dev
      - name: Setup dummy Git identity
        run: git config --global user.name "dummy" && git config --global user.email "dummy@example.com"
      - name: Run tests
        run: make ci
  linux-coverage:
    runs-on: ubuntu-latest
    needs: linux-test
    container:
      image: xd009642/tarpaulin:latest
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v3
      - name: Setup dummy Git identity
        run: git config --global user.name "dummy" && git config --global user.email "dummy@example.com"
      - name: Install libgit2
        run: apt-get update -y && apt-get install -y libgit2-dev
      - name: Run tests with coverage
        run: cargo tarpaulin --verbose
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
