name: test

on:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**/*.md'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.event.repository.name }}
  CARGO_TERM_COLOR: always

jobs:
  linux-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install libgit2
        run:  sudo apt-get install -y libgit2-dev
      - name: Setup dummy Git identity
        run: git config --global user.name "dummy" && git config --global user.email "dummy@example.com"
      - name: Run tests
        run: make ci

  linux-coverage:
    runs-on: ubuntu-latest
    needs: linux-test
    steps:
      - uses: actions/checkout@v4
      - name: Setup dummy Git identity
        run: git config --global user.name "dummy" && git config --global user.email "dummy@example.com"
      - name: Install libgit2
        run: sudo apt-get update -y && sudo apt-get install -y libgit2-dev
      - name: Install Rust
        run: rustup update stable
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run tests with coverage
        run: make coverage
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          files: lcov.info
  linux-build-flake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: make flake

